version: '3'
services: 

    mongodb:
        image: mongo
        container_name: "mongodb"
        ports: [27017:27017]
        env_file: .env
        restart: unless-stopped
        command: mongod --auth
        volumes: [./data/mongodb:/data/db]


    device-service:
        image: ghcr.io/mp281x/device-service:latest
        container_name: "device-service"
        ports: [9090:9090]
        env_file: .env
        restart: unless-stopped
        depends_on: [mongodb]
        # volumes: 
        #     - ./data/log:/app/log
        #     - ./certs:/app/certs
    
    file_storage-service:
        image: ghcr.io/mp281x/file_storage-service:latest
        container_name: "file_storage-service"
        # ports: [9091:9091, 443:9094, 80:9095]
        ports: [9091:9091, 8080:9094]
        env_file: .env
        restart: unless-stopped
        depends_on: [mongodb]
        volumes: 
            - ./data/asset:/app/asset
            # - ./data/log:/app/log
            # - ./web:/app/web
            # - ./certs:/app/certs

    rom-service:
        image: ghcr.io/mp281x/rom-service:latest
        container_name: "rom-service"
        ports: [9092:9092]
        env_file: .env
        restart: unless-stopped
        depends_on:  [mongodb]
        # volumes: 
        #     - ./data/log:/app/log
        #     - ./certs:/app/certs

    user-service:
        image: ghcr.io/mp281x/user-service:latest
        container_name: "user-service"
        ports: [9093:9093]
        env_file: .env
        restart: unless-stopped
        depends_on: [mongodb]
        # volumes: 
        #     - ./data/log:/app/log
        #     - ./certs:/app/certs

    # grafana:
    #     image: grafana/grafana:latest
    #     container_name: "grafana"
    #     ports: [3000:3000]
    #     env_file: .env
    #     restart: unless-stopped
    #     depends_on: [influxdb]
    #     volumes: [./data/grafana:/var/lib/grafana]

    # influxdb:
    #     image: influxdb:latest
    #     container_name: "influxdb"
    #     ports: [8086:8086]
    #     env_file: .env
    #     restart: unless-stopped
    #     volumes: 
    #         - ./data/influxdb/influx-data:/var/lib/influxdb2
    #         - ./data/influxdb/influx-config:/etc/influxdb2
       